name: recursive_reasoning.trm@TinyRecursiveReasoningModel_ACTV1
loss:
  name: losses@VariantClassificationHead

halt_exploration_prob: 0.0
halt_max_steps: 4

H_cycles: 1
L_cycles: 2

H_layers: 0
L_layers: 2

hidden_size: 256
num_heads: 4
expansion: 4

puzzle_emb_ndim: 0
puzzle_emb_len: 0

pos_encodings: rope
forward_dtype: bfloat16

mlp_t: False
no_ACT_continue: True
