# ClinVar longer training config (10k dataset ready)

defaults:
  - arch: variant_trm
  - _self_

hydra:
  output_subdir: null

data_paths: ['data/clinvar/processed/clinvar_trm']
data_paths_test: ['data/clinvar/processed/clinvar_trm']

evaluators:
  - name: clinvar@ClinVarEvaluator

global_batch_size: 256

epochs: 50
eval_interval: 5
checkpoint_every_eval: True

lr: 5e-4
lr_min_ratio: 0.1
lr_warmup_steps: 500

beta1: 0.9
beta2: 0.95
weight_decay: 0.01
puzzle_emb_weight_decay: 0.0

puzzle_emb_lr: 0.0

seed: 42
min_eval_interval: 0

ema: False
freeze_weights: False
